name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - run: dotnet restore
    
    - run: dotnet build -c Release --no-restore
    
    - run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
